# docker-compose.app.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    networks:
      - app-network
      - db-network
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

networks:
  app-network:
    driver: bridge
  db-network:
    external: true
