# docker-compose.db.yml
version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - db-network
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data:

networks:
  db-network:
    name: db-network
    driver: bridge